### ISSUE TITLE
Updates Embed Messages (if possible)

### ISSUE THREAD

**Issue by Mazmol** [Rushnett/starboard#29]
Either a command or something to basically reload the embed. 

For example if you create a message and star it and then go back and make a change to message you have to remove reactions and re add it. 

Command could be a simple as /reloadStarboard link to message and remove all reactions and re star it.

**Comment by naeruru** [comment]
I can work on adding that after https://github.com/naexris/starboard/pull/28. I can also make it automatic with [onMessageUpdate](https://discord.js.org/#/docs/discord.js/main/class/Client?scrollTo=e-messageUpdate) or updating it on next react, but I never did this before because I was afraid of abuse. Maybe I can just make that way optional in the config

**Comment by Erisa** [comment]
> Maybe I can just make that way optional in the config

This sounds like a good compromise to me

**Comment by Mazmol** [comment]
thanks you, no rush btw <3

**Comment by naeruru** [comment]
sorry for wait on this. spread myself thin with school/work/thesis/personal projects. I pushed a super experimental commit in [dev-v1.6.2-TEMP](https://github.com/naexris/starboard/tree/dev-v1.6.2-TEMP). I did not test it fully yet but it works pretty well so far if you just want to clone it and use it.  requires `"editOnMsgUpdate": true` in `settings.json`. See [settings.json.example](https://github.com/naexris/starboard/blob/dev-v1.6.2-TEMP/config/settings.json.example#L11).

example~

https://user-images.githubusercontent.com/9059594/234446637-54686fb3-9606-4c5a-931b-ff58751f6261.mp4

### long message about my thoughts on next steps in 3.... 2... 1....

...but the thing is, I was writing the code a couple weeks ago and I don't really like how I was doing it or how this feature works. Maybe others do? but I just wasn't in love. (feel free to change my mind)
- it felt too easy to abuse
- it is annoying to toggle it on and off (config dependent)
- what if you only want some users to have the ability?
- etc....

by the time I finished it, I had changed the structure of the code a lot. I realized halfway through I could bundle this into the next feature I want to work on and make it way more secure/customizable.  that next feature is adding slash commands / right click context menus to allow users to do basic features easier like setting up the bot, editing configs, updating embeds, adding multiple boards, and so on. because of that, I started to adjust the structure of the code to better suit that plan. so, while this single commit doesn't do a lot, it changed a ton of the code. I will probably be changing a lot from this commit still. so, it is completely experimental and if you don't want this feature I recommend just staying on main branch for now. but if you do want this feature, feel free to try it out. starboard still fundamentally works exactly the same, the functions are just more modularized (not quite to the point I want it yet though).


### SUMMARY: 
I want to add slash commands to do a lot of features. you will be able to just right click an embed and say "fetch latest" instead. I think that way is way way better. instant updates can be abused way too easy (though i dont mind making it an option). I am going to try my best to preserve the small footprint of the app while adding this. the slash commands will be totally optional.

*phew*


EDIT:
possible ideas to make the edit feature better:
- grace period
- add a note that says the embed was edited

**Comment by Mazmol** [comment]
This is fucking awsome thank you so much ❤️ mate I said take your time and don't rush it. I been in the same boat with uni work etc. appreciate everything you do and didn't have to do this :)

**Comment by Mazmol** [comment]
Started using Dev branch and Checked the Update worked perfectly - see if it breaks will let you know on feedback. yeah this can be abused. so I think it a command hidden behind / command permissions for exmple someone can run  (/fetchmsg) and will update the latest stars with the messages. the toggle to turn it on and off Its not annoying tbh its perfect but if possible link the config to a command? not sure if possible !togglemessageupdate on / off similar how a blacklist works for words and you can toggle it. 

My other part of confiig setup. works nicely. 
![image](https://user-images.githubusercontent.com/38956955/235303836-9bb2031e-b552-4088-a1cd-caf980652fd7.png)

to keep it so only some peohave the abbility link it to a use role so more permission handling
![WqSbVCE](https://user-images.githubusercontent.com/38956955/235303969-fc24f49d-a536-4ca7-a3a7-fa6b5c6546da.png)

other then that its perfect thanks again @naexris

**Comment by naeruru** [comment]
feature will be addressed in https://github.com/naexris/starboard/pull/33. backwards compatible and completely optional. no additional complexity was added if you dont use the feature (except an if/else check). decided to hold off on a lot of the bigger stuff
